### ISSUE TITLE
TypeError: Cannot read property 'setNativeProps' of null

### ISSUE THREAD

**Issue by javc86** [react-native-community/react-native-maps#2405]
I applyed the #889 solution, but it don't work for me. Here my code:

```import 'react-native';
import React, {Component, createElement} from 'react';
import {Provider} from 'react-redux';
import renderer from 'react-test-renderer';
import configureMockStore from 'redux-mock-store';
import Proptypes from 'prop-types';
import Maps from '../../app/src/screens/Maps';

const mockStore = configureMockStore();
const store = mockStore({});

jest.mock('react-native-maps', () => (
    class MockMapView extends Component {
      static Marker = props => createElement('Marker', props, props.children);

      static propTypes = {
          children: Proptypes.any.isRequired
      };

      render() {
          const {children} = this.props;
          return createElement('MapView', this.props, children);
      }
    }
));

it('renders correctly', () => {
    const navigation = {navigate: jest.fn()};

    const tree = renderer.create(
        <Provider store={store}>
            <Maps navigation={navigation}/>
        </Provider>
    ).toJSON();
    expect(tree).toMatchSnapshot();
});
```
Maps component

```import React, {Component} from 'react';
import {
    View,
    BackHandler,
    Animated
} from 'react-native';
import {bindActionCreators} from 'redux';
import {connect} from 'react-redux';
import Proptypes from 'prop-types';
import MapView, {UrlTile, Marker, Callout} from 'react-native-maps';
import Picker from 'react-native-picker';
import styles from './styles';
import * as actions from '../../modules/projects/reducers';

import ServicesInfoBox from '../../components/ServicesInfoBox';
import ServiceNoOkDetailBox from '../../components/ServiceNoOkDetailBox';
import ArrowBack from '../../components/ArrowBack';

class Maps extends Component {
    static navigationOptions = {
        header: null
    }

    static propTypes = {
        // projects: Proptypes.shape({}).isRequired,
        navigation: Proptypes.shape({
            navigate: Proptypes.func.isRequired
        }).isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            initialRegion: {
                latitude: -34.5737,
                longitude: -58.4630,
                latitudeDelta: 0.005,
                longitudeDelta: 0
            },
            markerLatLng: {
                latitude: -34.5737,
                longitude: -58.4630
            },
            services: [
                {
                    name: 'Luz',
                    status: 'no-ok',
                    icon: 'lightbulb-o'
                },
                {
                    name: 'Internet',
                    status: 'no-ok',
                    icon: 'wifi'
                },
                {
                    name: 'Cable',
                    status: 'ok',
                    icon: 'television'
                },
                {
                    name: 'Luz',
                    status: 'ok',
                    icon: 'phone'
                }
            ],
            showServiceNoOkDetailBox: false,
            animate: new Animated.Value(0)
        };
    }

    componentDidMount() {
        this.backHandler = BackHandler.addEventListener('hardwareBackPress', () => {
            this.handleBackPress();
            return true;
        });
    }

    componentWillUnmount() {
        this.backHandler.remove();
    }

    handleBackPress() {
        const {navigation} = this.props;
        navigation.goBack();
    }

    createDateData() {
        const {services} = this.state;

        const servicesNoOk = [];

        services.forEach(service => {
            if (service.status === 'no-ok') {
                servicesNoOk.push(service.name);
            }
        });

        return servicesNoOk;
    }

    render() {
        const {
            initialRegion,
            services,
            showServiceNoOkDetailBox,
            markerLatLng,
            animate
        } = this.state;

        const onShowHideServiceNoOkDetailBox = () => {
            if (!showServiceNoOkDetailBox) {
                Animated.timing(animate, {
                    toValue: 250,
                    duration: 800
                }).start();
            } else {
                Animated.timing(animate, {
                    toValue: 0,
                    duration: 800
                }).start();
            }

            this.setState({
                showServiceNoOkDetailBox: !showServiceNoOkDetailBox
            });
        };

        const showDatePicker = () => {
            Picker.init({
                pickerData: this.createDateData(),
                pickerFontColor: [255, 0, 0, 1],
                onPickerConfirm: (pickedValue, pickedIndex) => {
                    console.log('date', pickedValue, pickedIndex);
                    onShowHideServiceNoOkDetailBox();
                },
                onPickerCancel: (pickedValue, pickedIndex) => {
                    console.log('date', pickedValue, pickedIndex);
                },
                onPickerSelect: (pickedValue, pickedIndex) => {
                    console.log('date', pickedValue, pickedIndex);
                }
            });
            Picker.show();
        };

        const back = () => {
            const {navigation} = this.props;
            navigation.goBack();
        };

        return (
            <View style={styles.container}>
                <ArrowBack back={back}/>
                <MapView
                    provider={null}
                    mapType="none"
                    style={styles.map}
                    initialRegion={initialRegion}
                >
                    <UrlTile
                        urlTemplate="http://c.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        maximumZ={20}
                    />
                    <Marker
                        coordinate={markerLatLng}
                    >
                        <Callout
                            style={styles.callout}
                            onPress={() => showDatePicker()}
                        >
                            <ServicesInfoBox
                                services={services}
                            />
                        </Callout>
                    </Marker>
                </MapView>
                <ServiceNoOkDetailBox
                    address="Escobar 3101, CABA"
                    onShowHideServiceNoOkDetailBox={onShowHideServiceNoOkDetailBox}
                    animate={animate}
                />
            </View>
        );
    }
}

const mapStateToProps = state => ({projects: state.projects});
const mapDispatchToProps = dispatch => (bindActionCreators(actions, dispatch));

export default connect(mapStateToProps, mapDispatchToProps)(Maps);
```
Package.js
```{
  "name": "BLK",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "reset": "react-native start --reset-cache",
    "android": "react-native run-android",
    "test": "jest",
    "eslint": "./node_modules/.bin/eslint app/src/",
    "commitmsg": "npm run eslint && commitlint -e .git/COMMIT_EDITMSG"
  },
  "dependencies": {
    "lodash": "^4.17.10",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-animatable": "^1.3.0",
    "react-native-elements": "^0.19.1",
    "react-native-maps": "^0.21.0",
    "react-native-picker": "^4.3.7",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.6.2",
    "react-navigation-redux-helpers": "^2.0.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.54",
    "@commitlint/cli": "^7.0.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.6",
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "^5",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jest": "^21.18.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "husky": "^0.14.3",
    "jest": "23.4.1",
    "jest-config": "^23.4.1",
    "react-test-renderer": "^16.4.1",
    "redux-mock-store": "^1.5.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "js",
      "jsx",
      "json"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|react-native-maps|babel-preset-react-native|prop-types|react-native-animatable|react-native-picker|react-native-elements|react-native-vector-icons)/)"
    ]
  }
}
```

 The error

> renders correctly

    TypeError: this.map.setNativeProps is not a function

      at MapView._updateStyle (node_modules/react-native-maps/lib/components/MapView.js:490:16)
      at MapView.componentDidMount (node_modules/react-native-maps/lib/components/MapView.js:484:14)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6444:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7540:7)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1841:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1986:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7681:7)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8650:34)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8595:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8527:7)

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
