### ISSUE TITLE
NoMethodError - undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by sludosky** [react-native-community/react-native-maps#2443]
### Command

```
/usr/local/bin/pod spec lint TrackerPod.podspec --no-clean --use-libraries
```

### Report

* What did you do?
pod install
pod spec lint *pod name*.podspec --no-clean --use-libraries
the goal is to run pod lint for a new podspec 
* What did you expect to happen?
podspec validation
* What happened instead?
podspec validation fails

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 905f1befd6a070af8e0c759df00c69ab8878c2e7
               **** - ***** @ 01fc4a240896b442ebcc00ce10b8ca79c3ba8da5
                ***** @ 01fc4a240896b442ebcc00ce10b8ca79c3ba8da5
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target '*****' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for **********
  pod 'MatomoTracker', '~> 5.2'
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:253:in `validation_dir'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/spec/lint.rb:74:in `block in run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/spec/lint.rb:57:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/spec/lint.rb:57:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by christopherdro** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks!
