### ISSUE TITLE
Crash on Android devices

### ISSUE THREAD

**Issue by erez-guesty** [react-native-community/react-native-maps#2597]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
react-native: 0.55.0
react: 16.4.0
android:
  compileSdkVersion: 26
  buildToolsVersion: 26.0.2
  minSdkVersion 16
  targetSdkVersion 26

```
implementation(project(':react-native-maps')){
         exclude group: 'com.google.android.gms', module: 'play-services-base'
         exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
```

### Steps to Reproduce
1. assimilate **react-native-maps** in RN project.
2. import map components.
3. implement simple usage of map components.
4. luanch app on Android devices
```
import MapView, { Marker } from 'react-native-maps';

render() {
 return (
      <MapView  initialRegion={{ ... }}>
        <Marker
          coordinate={{ ... }}
           title={...}
             description={...}>
            <Image source={...} />
         </Marker>
       </MapView>
    );
  }
```

### Expected Behavior
render map with marker.

### Actual Behavior
crash.

```
Caused by java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.Double
       at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:147)
       at com.facebook.react.bridge.DynamicFromMap.asDouble(DynamicFromMap.java:64)
       at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:64)
       at com.facebook.react.uimanager.LayoutShadowNode.setHeight(LayoutShadowNode.java:154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
       at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
       at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
       at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:171)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by miracle2k** [comment]
It sounds like something might be wrong with your `coordinate`  or `initialRegion` structures - the library is likely to try to read a `double` from there.

**Comment by rborn** [comment]
Closing, old issue.
