### ISSUE TITLE
Crash with null Location in FusedLocationSource

### ISSUE THREAD

**Issue by netshade** [react-native-community/react-native-maps#3344]
# Bug

In some cases where `getLastLocation` returns `null`, the `null` location provided in the success listener is incorrectly passed to `onLocationChanged`. This then causes a crash later downstream, as seen in this stack trace from a Detox run:

```
   androidx.test.espresso.PerformException: Error performing 'com.wix.detox.espresso.action.detoxsingletap@1305bed click - At Coordinates: 521, 1250 and precision: 16, 16' on view '(with tag value: is "NewReport-Next" and view has effective visibility=VISIBLE)'.
    	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
    	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:87)
    	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
    	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
    	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
    	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
    	at com.wix.detox.espresso.EspressoDetox.perform(EspressoDetox.java:40)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:443)
    	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
    	at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
    	at com.wix.invoke.types.Target.invoke(Target.java:59)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
    	at com.wix.detox.InvokeActionHandler.handle(DetoxActionHandlers.kt:52)
    	at com.wix.detox.DetoxManager$4.run(DetoxManager.java:121)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loop(Looper.java:214)
    	at com.wix.detox.Detox$1.run(Detox.java:135)
    	at java.lang.Thread.run(Thread.java:919)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
    	at com.google.maps.api.android.lib6.gmm6.api.n.a(:com.google.android.gms.dynamite_mapsdynamite@19275052@19.2.75 (040700-269183835):18)
    	at com.google.maps.api.android.lib6.impl.dk.a(:com.google.android.gms.dynamite_mapsdynamite@19275052@19.2.75 (040700-269183835):29)
    	at com.google.android.gms.maps.internal.as.a(:com.google.android.gms.dynamite_mapsdynamite@19275052@19.2.75 (040700-269183835):3)
    	at cv.onTransact(:com.google.android.gms.dynamite_mapsdynamite@19275052@19.2.75 (040700-269183835):4)
    	at android.os.Binder.transact(Binder.java:914)
    	at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
    	at com.google.android.gms.maps.internal.zzai.zza(Unknown Source:5)
    	at com.google.android.gms.maps.zzm.onLocationChanged(Unknown Source:2)
    	at com.airbnb.android.react.maps.FusedLocationSource$1.onSuccess(FusedLocationSource.java:46)
    	at com.airbnb.android.react.maps.FusedLocationSource$1.onSuccess(FusedLocationSource.java:43)
    	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
    	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:525)
    	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:447)
    	at androidx.test.espresso.base.UiControllerImpl.injectMotionEventSequence(UiControllerImpl.java:308)
    	at com.wix.detox.espresso.action.DetoxSingleTap.sendTap(DetoxSingleTap.kt:37)
    	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:137)
    	at com.wix.detox.espresso.action.RNClickAction.perform(RNClickAction.java:55)
    	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
    	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
    	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
    	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
    	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loop(Looper.java:214)
    	at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 2.78 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.19.0 - /var/folders/tz/2rsql3g94gb6p4c_07g13mpm0000gn/T/yarn--1584471146063-0.42442311479591677/node
    Yarn: 1.22.0 - /var/folders/tz/2rsql3g94gb6p4c_07g13mpm0000gn/T/yarn--1584471146063-0.42442311479591677/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.0, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
```

Library version: 0.27.0

## Steps To Reproduce

Reproduction is not trivial, only occurs in our Detox CI.

## Reproducible sample code

See above re: reproduction.

## Notes

This falls into a logical bug category, if only due to the fact:

1. The documentation for [`getLastLocation`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#getLastLocation()) states that `getLastLocation` may provide a `null` `Location` in some occasions
1. ...yet the documentation for [`onLocationChanged`](https://developers.google.com/android/reference/com/google/android/gms/maps/LocationSource.OnLocationChangedListener) specifically states that no `null` `Location` should be provided as the `Location` argument.

**Comment by netshade** [comment]
Addressed by #3345.
